openapi: 3.0.0
info:
  version: '1.0'
  title: e222_project
  description: ''
paths:
 /pred/{arg}:
    get:
      tags:
        - PRED
      operationId: my_python_dir.HF_defaultservice.ipynb.my_prediction
      description: returns prediction of ML application

 /score/{arg}:
    get:
      tags:
        - SCORE
      operationId: my_python_dir.HF_defaultservice.ipynb.score
      description: Returns score of model

servers:
  - url: 'http://localhost:8080/engr-222'